# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True, verbose_name='Title')),
                ('content', models.TextField(blank=True, max_length=200, null=True, verbose_name='Content')),
                ('discoverable', models.BooleanField(default=True, help_text='Make visible to public')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
