# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='This entry is automatically generated', verbose_name='Blog ID/Suburl'),
        ),
    ]
