# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blogsmodel__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='discoverable',
            field=models.BooleanField(default=True, help_text='Visible to public'),
        ),
    ]
