# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_auto_20170107_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='This entry is automatically generated', verbose_name='Blog ID(Sub-URL)'),
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Content'),
        ),
    ]
