# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_auto_20170109_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='content',
            field=models.TextField(blank=True, help_text='Word limit is 10000 characters', max_length=10000, null=True, verbose_name='Content'),
        ),
    ]
